before_script:
    - apt-get update -qq && apt-get install -y -qq pip
    - pip install -r test_requirements.txt
    - git clone https://gitlab.com/DukeValentine/nhentai-downloader.git
    - cd nhentai-downloader
    - python setup.py install


test:
  script:
    - nhentai-downloader --help
    
test0:
  script:
    - nhentai-downloader --search --verbose -t sword english --json --output test0.json
    
test1:
  script:
    - nhentai-downloader --search --verbose -t english --max-page 4 --json --output test1.json
    
test2:
  script:
    - nhentai-downloader --verbose --id 253293 251830 248899 232365 233068 --json --output test2.json
    
test3:
  script:
   - nhentai-downloader --verbose --id 253293 251830 248899 232365 233068 --download --json --output test3.json
   
test4:
  script:
   - nhentai-downloader --verbose --debug --id 253293
   - nhentai-downloader --verbose -t sword english
