image: registry.gitlab.com/dukevalentine/nhentai-downloader:latest

variables:
    BINARY_BASENAME: "nhentai-downloader-dev"
    BINARY_NAME: "nhentai-downloader-dev.exe"


before_script:
    - ls
    
install:
  stage: build
  script:
      - ls
      - python setup.py develop
      - nhentai-downloader --help
      - ls
    

test:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --help
    - nhentai-downloader --login $NHENTAI_USER --password $NHENTAI_PASS --verbose --debug --max-page 3 --torrent
    
test0:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --search --verbose -t sword english --json --output test0.json --max-page 1 --download --cbz --remove-after
    - ls nhentai
    
test1:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --search --verbose -t english --max-page 4 --json --output test1.json
    - ls nhentai
    
test2:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --verbose --id 253293 251830 248899 232365 233068 --json --output test2.json
    - ls nhentai
    
test3:
  stage: test
  before_script:
    - python setup.py develop
  script:
   - ls
   - nhentai-downloader --verbose --id 253293 251830 248899 232365 233068 --download --json --output test3.json --torrent --cbz
   - ls -la nhentai
   - du -sh nhentai
   
test4:
  before_script:
   - python setup.py develop
  script:
   - ls
   - nhentai-downloader --verbose --debug --id 253293
   - nhentai-downloader --verbose -t sword english --max-page 1 --download --search
   - ls -la nhentai
   - du -sh nhentai
   
pypi:
  stage: deploy
  only:
  - dev
  only:
  - tags
  only:
  - /^v[0-9](?:\.[0-9]+){2,4}/
  
  before_script:
  - python setup.py sdist

  script:
  - twine upload dist/*.tar.gz --skip-existing


