image: registry.gitlab.com/dukevalentine/nhentai-downloader:latest

before_script:
    - ls

    
install:
  stage: build
  script:
      - ls
      - python setup.py develop
      - nhentai-downloader --help
      - ls
    

test:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --help
    - nhentai-downloader --login $NHENTAI_USER --password $NHENTAI_PASS --verbose --debug --max-page 3 --torrent
    
test0:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --search --verbose -t sword english --json --output test0.json
    - ls nhentai
    
test1:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --search --verbose -t english --max-page 4 --json --output test1.json
    - ls nhentai
    
test2:
  stage: test
  before_script:
    - python setup.py develop
  script:
    - ls
    - nhentai-downloader --verbose --id 253293 251830 248899 232365 233068 --json --output test2.json
    - ls nhentai
    
test3:
  stage: test
  before_script:
    - python setup.py develop
  script:
   - ls
   - nhentai-downloader --verbose --id 253293 251830 248899 232365 233068 --download --json --output test3.json --torrent
   - ls -la nhentai
   - du -sh nhentai
   
test4:
  stage: test
  before_script:
   - python setup.py develop
  script:
   - ls
   - nhentai-downloader --verbose --debug --id 253293
   - nhentai-downloader --verbose -t sword english --max-page 2 --download --search
   - ls -la nhentai
   - du -sh nhentai
   
pypi:
  stage: deploy
  only:
  - master
  only:
  - tags
  only:
  - /^v[0-9]+.[0-9]+.[0-9]+[0-9]?/

   
  before_script:
  - pip install twine
  - python setup.py sdist
  - wine pyinstaller ./nhentai_downloader/nhentai.py -F -p ./nhentai_downloader --hidden-import=requests,bs4 --clean --add-data ".commit_date;data" --name nhentai-downloader
  - ls ./dist
  - export BINARY_MARKDOWN=$(curl --request POST --header "PRIVATE-TOKEN:$PRIVATE_TOKEN" --form "file=@./dist/$BINARY_NAME" $CI_API_V4_URL/projects/$CI_PROJECT_ID/uploads | jq -r '.markdown')
   
  script:
  - twine upload dist/*.tar.gz --skip-existing
  - curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" --data '{ "name": "$CI_COMMIT_TITLE", "tag_name": "$CI_COMMIT_TAG", "description": "### $BINARY_MARKDOWN" }' --request POST $CI_API_V4_URL/projects/$CI_PROJECT_ID/releases
